apiVersion: v1
kind: ConfigMap
metadata:
  name: assetflow-trade-service-config
  labels:
    app: assetflow-trade-service
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8084"
  SPRING_CLOUD_CONFIG_URI: "http://assetflow-config-server:8888"
  KAFKA_BOOTSTRAP_SERVERS: "assetflow-kafka:9092"
  MARKET_DATA_SERVICE_BASE_URL: "http://assetflow-market-data-service:8083"
