apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assetflow-alert-mongo-pvc
  labels:
    app: assetflow-alert-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
