apiVersion: v1
kind: ConfigMap
metadata:
  name: assetflow-alert-mongo-initdb-config
  labels:
    app: assetflow-alert-mongo
data:
  init-mongo-alerts.js: |
    db = db.getSiblingDB("alerts");

    db.createUser({
        user: "sothrose",
        pwd: "sothrose",
        roles: [{ role: "readWrite", db: "alerts" }]
    });
