apiVersion: v1
kind: ConfigMap
metadata:
  name: assetflow-market-data-service-config
  labels:
    app: assetflow-market-data-service
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8083"
  SPRING_CLOUD_CONFIG_URI: "http://assetflow-config-server:8888"
  COIN_GECKO_URL: "https://api.coingecko.com/api/v3"
