apiVersion: v1
kind: ConfigMap
metadata:
  name: assetflow-user-service-config
  labels:
    app: assetflow-user-service
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://assetflow-user-service-db:5432/assetflow-user-service-db"
  SPRING_CLOUD_CONFIG_URI: "http://assetflow-config-server:8888"
