apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assetflow-user-service-db-pvc
  labels:
    app: assetflow-user-service-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
