apiVersion: v1
kind: Service
metadata:
  name: assetflow-user-service-db
  labels:
    app: assetflow-user-service-db
spec:
  selector:
    app: assetflow-user-service-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
