apiVersion: v1
kind: Secret
metadata:
  name: assetflow-trade-service-secret
  labels:
    app: assetflow-trade-service
type: Opaque
data:
  SPRING_DATA_MONGODB_URI: bW9uZ29kYjovL3NvdGhyb3NlOnNvdGhyb3NlQGFzc2V0Zmxvdy10cmFkZS1tb25nbzoyNzAxNy90cmFkZXM=
