apiVersion: v1
kind: Service
metadata:
  name: assetflow-config-server
  labels:
    app: assetflow-config-server
spec:
  selector:
    app: assetflow-config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
