apiVersion: v1
kind: Service
metadata:
  name: assetflow-portfolio-redis
spec:
  selector:
    app: assetflow-portfolio-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
