apiVersion: apps/v1
kind: Deployment
metadata:
  name: assetflow-zookeeper
  labels:
    app: assetflow-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assetflow-zookeeper
  template:
    metadata:
      labels:
        app: assetflow-zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          envFrom:
            - configMapRef:
                name: assetflow-zookeeper-config
