apiVersion: v1
kind: Service
metadata:
  name: assetflow-trade-service
  labels:
    app: assetflow-trade-service
spec:
  selector:
    app: assetflow-trade-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30084
