apiVersion: v1
kind: ConfigMap
metadata:
  name: assetflow-alert-service-config
  labels:
    app: assetflow-alert-service
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8085"
  SPRING_CLOUD_CONFIG_URI: "http://assetflow-config-server:8888"
  KAFKA_BOOTSTRAP_SERVERS: "assetflow-kafka:9092"
