apiVersion: v1
kind: ConfigMap
metadata:
  name: assetflow-portfolio-service-config
  labels:
    app: assetflow-portfolio-service
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8082"
  SPRING_CLOUD_CONFIG_URI: "http://assetflow-config-server:8888"
  USER_SERVICE_BASE_URL: "http://assetflow-user-service:8081"
  USER_SERVICE_USER_BY_ID_PATH: "/v1/assetflow/users/{userId}"
  KAFKA_BOOTSTRAP_SERVERS: "assetflow-kafka:9092"
  ASSETFLOW_PORTFOLIO_REDIS_HOST: "assetflow-portfolio-redis"
  ASSETFLOW_PORTFOLIO_REDIS_PORT: "6379"