apiVersion: v1
kind: Service
metadata:
  name: assetflow-alert-mongo
  labels:
    app: assetflow-alert-mongo
spec:
  selector:
    app: assetflow-alert-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
