apiVersion: v1
kind: Service
metadata:
  name: assetflow-zookeeper
  labels:
    app: assetflow-zookeeper
spec:
  selector:
    app: assetflow-zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  clusterIP: None
