apiVersion: v1
kind: Service
metadata:
  name: assetflow-kafka
  labels:
    app: assetflow-kafka
spec:
  selector:
    app: assetflow-kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: kafka-client
    - protocol: TCP
      port: 9093
      targetPort: 9093
      name: kafka-internal
  clusterIP: None
