apiVersion: v1
kind: Service
metadata:
  name: assetflow-api-gateway
spec:
  selector:
    app: assetflow-api-gateway
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
