apiVersion: v1
kind: Service
metadata:
  name: assetflow-user-service
  labels:
    app: assetflow-user-service
spec:
  selector:
    app: assetflow-user-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
